"""HousePrice-AI — Streamlit prediction app (Phase 6).

A portfolio-grade front end for the trained XGBoost model. Users enter house
characteristics; the app builds a complete raw input row and runs it through
the **exact same preprocessing / feature-engineering / one-hot alignment used
during training** (see ``src/models/predict.py``), then reverses the log1p
training target with ``np.expm1``.

No model is trained here and no prediction is ever hard-coded — every estimate
comes from ``models/best_model.joblib``.

Run from the project root:

    streamlit run app.py
"""

from __future__ import annotations

import streamlit as st

from src.config import PATHS
from src.features.preprocessing import QUALITY_ORDINAL
from src.models.predict import load_model_artifact, options_for, predict_price

st.set_page_config(page_title="HousePrice-AI", page_icon="🏠", layout="wide")

MODEL_READY = PATHS.best_model.is_file()

# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------
with st.sidebar:
    st.header("About")
    st.write(
        "**HousePrice-AI** — an end-to-end ML project for the Kaggle "
        "**House Prices — Advanced Regression Techniques** competition "
        "(Ames Housing dataset)."
    )
    st.markdown(
        "[Kaggle competition page](https://www.kaggle.com/competitions/"
        "house-prices-advanced-regression-techniques)"
    )
    st.divider()

    if MODEL_READY:
        artifact = load_model_artifact()
        st.subheader("Model")
        st.write(f"Algorithm: **XGBoost** (tuned)")
        st.write(f"Target: **log1p(SalePrice)** → `np.expm1()`")
        st.write(f"Features: **{len(artifact['feature_columns'])}**")
        st.caption("5-fold CV log-RMSE ≈ 0.1270 · Kaggle score 0.12656")
    else:
        st.subheader("Model")
        st.write("❌ **No trained model found**")

    st.divider()
    st.caption(
        "Predictions are **estimates**, not guaranteed market prices. "
        "They are generated by the trained model from the information "
        "entered — no manual adjustments, no fabricated numbers."
    )

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------
st.title("🏠 HousePrice-AI")
st.subheader("Estimate house prices in Ames, Iowa")

if not MODEL_READY:
    st.warning(
        "No trained model found at "
        f"`{PATHS.best_model}`. "
        "The estimator is disabled **on purpose** — this project never shows "
        "made-up numbers. Train the model first with "
        "`python -m src.models.train` (see README)."
    )
    st.stop()

artifact = load_model_artifact()
feature_columns = artifact["feature_columns"]


def _levels(column: str) -> list[str]:
    """Category levels of a one-hot encoded column, from the artifact."""
    return options_for(feature_columns, column)


def _ordinal_levels(column: str) -> list[str]:
    """Levels of an ordinal column, excluding the 'None' (absent) marker."""
    return [lvl for lvl in QUALITY_ORDINAL[column] if lvl != "None"]


def _preferred_index(options: list[str], preferred: str) -> int:
    try:
        return options.index(preferred)
    except ValueError:
        return 0


# ---------------------------------------------------------------------------
# Input form
# ---------------------------------------------------------------------------
st.markdown(
    "Describe a home below. Anything you leave at its default is filled with "
    "a typical value from the training set; the prediction is always produced "
    "by the trained XGBoost model."
)

with st.form("house_form"):
    features: dict = {}

    st.markdown("#### 1 · Location & basics")
    c1, c2, c3, c4 = st.columns(4)
    neighborhood = _levels("Neighborhood")
    features["Neighborhood"] = c1.selectbox(
        "Neighborhood", neighborhood, index=_preferred_index(neighborhood, "CollgCr")
    )
    mszoning = _levels("MSZoning")
    features["MSZoning"] = c2.selectbox(
        "MS Zoning", mszoning, index=_preferred_index(mszoning, "RL")
    )
    features["OverallQual"] = c3.slider("Overall quality (1–10)", 1, 10, 5)
    features["OverallCond"] = c4.slider("Overall condition (1–10)", 1, 10, 5)

    c1, c2, c3, c4 = st.columns(4)
    features["YearBuilt"] = c1.number_input(
        "Year built", min_value=1800, max_value=2025, value=1973, step=1
    )
    features["YearRemodAdd"] = c2.number_input(
        "Year remodelled", min_value=1800, max_value=2025, value=1978, step=1
    )
    features["LotArea"] = c3.number_input(
        "Lot area (sq ft)", min_value=0, value=9478, step=100
    )
    features["LotFrontage"] = c4.number_input(
        "Lot frontage (ft)", min_value=0, value=70, step=5
    )

    st.markdown("#### 2 · Size & rooms")
    c1, c2, c3, c4 = st.columns(4)
    features["GrLivArea"] = c1.number_input(
        "Above-grade living area (sq ft)", min_value=0, value=1464, step=50
    )
    features["TotalBsmtSF"] = c2.number_input(
        "Basement area (sq ft)", min_value=0, value=900, step=50
    )
    features["1stFlrSF"] = c3.number_input(
        "1st floor area (sq ft)", min_value=0, value=1162, step=50
    )
    features["2ndFlrSF"] = c4.number_input(
        "2nd floor area (sq ft)", min_value=0, value=0, step=50
    )

    c1, c2, c3, c4 = st.columns(4)
    features["FullBath"] = c1.selectbox("Full baths (above grade)", list(range(5)), index=2)
    features["HalfBath"] = c2.selectbox("Half baths (above grade)", list(range(3)), index=0)
    features["BedroomAbvGr"] = c3.selectbox("Bedrooms", list(range(7)), index=3)
    features["KitchenAbvGr"] = c4.selectbox("Kitchens", list(range(1, 4)), index=0)

    c1, c2, c3, c4 = st.columns(4)
    features["TotRmsAbvGrd"] = c1.selectbox("Total rooms", list(range(1, 15)), index=5)
    features["Fireplaces"] = c2.selectbox("Fireplaces", list(range(5)), index=0)
    c3.caption("")  # spacer keeps the grid tidy
    c4.caption("")

    st.markdown("#### 3 · Quality & condition")
    c1, c2, c3, c4 = st.columns(4)
    kq = _ordinal_levels("KitchenQual")
    features["KitchenQual"] = c1.selectbox(
        "Kitchen quality", kq, index=_preferred_index(kq, "TA")
    )
    eq = _ordinal_levels("ExterQual")
    features["ExterQual"] = c2.selectbox(
        "Exterior quality", eq, index=_preferred_index(eq, "TA")
    )
    ec = _ordinal_levels("ExterCond")
    features["ExterCond"] = c3.selectbox(
        "Exterior condition", ec, index=_preferred_index(ec, "TA")
    )
    hq = _ordinal_levels("HeatingQC")
    features["HeatingQC"] = c4.selectbox(
        "Heating quality", hq, index=_preferred_index(hq, "TA")
    )

    c1, c2, c3, c4 = st.columns(4)
    features["CentralAir"] = c1.selectbox("Central air", ["Y", "N"], index=0)
    bq = _ordinal_levels("BsmtQual")
    features["BsmtQual"] = c2.selectbox(
        "Basement quality", bq, index=_preferred_index(bq, "TA")
    )
    be = _ordinal_levels("BsmtExposure")
    features["BsmtExposure"] = c3.selectbox(
        "Basement exposure", be, index=_preferred_index(be, "No")
    )
    bf = _ordinal_levels("BsmtFinType1")
    features["BsmtFinType1"] = c4.selectbox(
        "Basement finish", bf, index=_preferred_index(bf, "Unf")
    )

    st.markdown("#### 4 · Garage & outdoor")
    c1, c2, c3, c4 = st.columns(4)
    features["GarageCars"] = c1.selectbox("Garage cars", list(range(5)), index=2)
    features["GarageArea"] = c2.number_input(
        "Garage area (sq ft)", min_value=0, value=480, step=50
    )
    gt = _levels("GarageType")
    features["GarageType"] = c3.selectbox(
        "Garage type", gt, index=_preferred_index(gt, "Attchd")
    )
    gf = _levels("GarageFinish")
    features["GarageFinish"] = c4.selectbox(
        "Garage finish", gf, index=_preferred_index(gf, "Unf")
    )

    c1, c2, c3, c4 = st.columns(4)
    features["PoolArea"] = c1.number_input(
        "Pool area (sq ft)", min_value=0, value=0, step=10
    )
    features["WoodDeckSF"] = c2.number_input(
        "Wood deck (sq ft)", min_value=0, value=0, step=50
    )
    features["OpenPorchSF"] = c3.number_input(
        "Open porch (sq ft)", min_value=0, value=0, step=50
    )
    fd = _levels("Fence")
    features["Fence"] = c4.selectbox(
        "Fence", fd, index=_preferred_index(fd, "None")
    )

    with st.expander("Advanced details (optional)"):
        c1, c2, c3, c4 = st.columns(4)
        hs = _levels("HouseStyle")
        features["HouseStyle"] = c1.selectbox(
            "House style", hs, index=_preferred_index(hs, "1Story")
        )
        bt = _levels("BldgType")
        features["BldgType"] = c2.selectbox(
            "Building type", bt, index=_preferred_index(bt, "1Fam")
        )
        fn = _levels("Foundation")
        features["Foundation"] = c3.selectbox(
            "Foundation", fn, index=_preferred_index(fn, "PConc")
        )
        rs = _levels("RoofStyle")
        features["RoofStyle"] = c4.selectbox(
            "Roof style", rs, index=_preferred_index(rs, "Gable")
        )

        c1, c2, c3, c4 = st.columns(4)
        e1 = _levels("Exterior1st")
        features["Exterior1st"] = c1.selectbox(
            "Exterior covering", e1, index=_preferred_index(e1, "VinylSd")
        )
        fu = _ordinal_levels("Functional")
        features["Functional"] = c2.selectbox(
            "Functionality", fu, index=_preferred_index(fu, "Typ")
        )
        stt = _levels("SaleType")
        features["SaleType"] = c3.selectbox(
            "Sale type", stt, index=_preferred_index(stt, "WD")
        )
        features["MoSold"] = c4.selectbox("Month sold", list(range(1, 13)), index=5)

        c1, c2 = st.columns(2)
        features["YrSold"] = c1.selectbox("Year sold", list(range(2006, 2011)), index=2)
        c2.caption("")

    submitted = st.form_submit_button("Estimate price", type="primary")

# ---------------------------------------------------------------------------
# Prediction result
# ---------------------------------------------------------------------------
if submitted:
    try:
        price = predict_price(features)
    except ValueError as exc:
        st.error(f"Could not estimate a price: {exc}")
    except Exception as exc:  # pragma: no cover - defensive
        st.error(f"Unexpected error while predicting: {exc}")
    else:
        st.success(f"### Estimated sale price: **${price:,.0f}**")
        st.caption(
            "Estimate produced by the trained XGBoost model on "
            f"{len(feature_columns)} features. This is a statistical estimate, "
            "not an appraisal or a guaranteed market price."
        )

# ---------------------------------------------------------------------------
# Explanation
# ---------------------------------------------------------------------------
st.divider()
st.markdown("## How this works")
st.markdown(
    """
- **What the model does** — predicts a home's `SalePrice` from 79 raw Ames
  Housing characteristics (quality ratings, sizes, rooms, garage, lot, ...).
- **The model** — a tuned **XGBoost** regressor trained on `log1p(SalePrice)`
  with 5-fold cross-validation (CV log-RMSE ≈ **0.1270**; private Kaggle
  score **0.12656**). The prediction path reverses the log transform with
  `np.expm1`.
- **Same pipeline as training** — your inputs are turned into a complete raw
  row and pushed through the identical `preprocess` → `engineer_features`
  → one-hot alignment used during training; unspecified features fall back to
  typical values from the training set. No second, ad-hoc pipeline.
- **Honest by design** — every estimate comes from the saved model artifact.
  Nothing is hard-coded or fabricated.
- **Please note** — predictions are **estimates**, not appraisals or
  guaranteed market prices. Use them for exploration and education.
"""
)
